### ISSUE TITLE
Why tags colours don't work

### ISSUE THREAD

**Issue by jarajto** [notion-enhancer/repo#68] opened 2022-02-04 11:33 UTC
**What is happening?**

Colours in tags/properties doesn't work in gruvbox dark theme

**What should be happening?**

Tags should have a coloured background

**Screenshots (if applicable):**

![unknown1](https://user-images.githubusercontent.com/79110777/152522339-d6c636de-2652-483a-b798-5b4c639aabb7.png)

![unknown](https://user-images.githubusercontent.com/79110777/152522345-3af74f5c-f580-4e09-a664-71509812509d.png)

**Operating system/browser name & version:**

Win 10

**notion-enhancer and/or notion-repackaged version:**

notion-repackaged

**notion-enhancer configuration (enabled/disabled mods and their settings):**

tweaks, title bar, tabs, outliner, simpler databases, indentation lines, bypass preview, weekly view, focus mode, collapsible headers, truncated titles, **gruvbox dark theme**

**Comment by Vermoot** [comment] 2022-02-14 22:36
I believe this is a duplicate of notion-enhancer/notion-enhancer#888. I'd like to see this resolved as well

**Closed as completed** 2022-02-15 03:11 UTC
Labels: bug, duplicate
